name: Auto-Merge
on:
  pull_request_target:
    types: [labeled]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "name ${{github.event.pull_request.user.name}}"
          echo "email ${{github.event.pull_request.user.email}}"
          echo "type ${{github.event.pull_request.user.type}}"
          echo "url ${{github.event.pull_request.user.url}}"
          echo "login ${{github.event.pull_request.user.login}}"
