# see https://github.com/marketplace/actions/merge-pull-requests-automerge-action
# don't forget the repo settings!
# i wonder why https://github.com/marketplace/actions/enable-github-automerge wasn't triggered
# https://github.com/hmarr/auto-approve-action seems dangerous
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,this-is-my-gun"
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase"
