name: triggered by PR merge

on:
    pull_request:
        types: [closed]

jobs:
    do-the-thing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: attempt to print the secret
              run: |
                my_magical_secret="${{secrets.MY_MAGICAL_SECRET}}"
                echo "hello world: ${my_magical_secret}"
                echo "goodbye world: ${my_magical_secret}"
            - name: print out the merged PR's details
              run: |
                echo "PR number: ${{github.event.pull_request.number}}"
                echo "PR title: ${{github.event.pull_request.title}}"
                echo "PR body: ${{github.event.pull_request.body}}"
                echo "PR merged: ${{github.event.pull_request.merged}}"
                echo "PR merged by: ${{github.event.pull_request.merged_by}}"

                # get the original commit sha for the PR
                echo "PR base sha (the original commit sha for the PR): ${{github.event.pull_request.base.sha}}"

                # get the last commit sha on the source branch of the PR
                echo "PR head sha (the last commit sha on the source branch): ${{github.event.pull_request.head.sha}}"

                echo "PR created at: ${{github.event.pull_request.created_at}}"
                created_timestamp="$(date -d"${{github.event.pull_request.created_at}}" +%s)"
                echo "PR created at: $created_timestamp"
                echo "PR merged at: ${{github.event.pull_request.merged_at}}"
                merged_timestamp="$(date -d"${{github.event.pull_request.merged_at}}" +%s)"
                echo "PR merged at: $merged_timestamp"
                pr_open_time_in_minutes=$(echo "($merged_timestamp - $created_timestamp) / 60" | bc)
                echo "time in minutes between PR open and merge: ${pr_open_time_in_minutes}m"

                echo "PR merge commit SHA (the commit sha on the target branch: ${{github.event.pull_request.merge_commit_sha}}"
                echo "full event body: ${{github.event}}"
                echo "event name: ${{github.event_name}}"

                first_commit_timestamp="$(git show -s --format=%ci ${{github.event.pull_request.base.sha}})"
                echo "base commit time using 'git show -s --format=%ci <COMMIT HASH>': $first_commit_timestamp"

                first_commit_timestamp=$(git log -1 --format=%ct ${{github.event.pull_request.base.sha}})
                echo "base commit time using 'git log -1 --format=%ct <COMMIT HASH>': $first_commit_timestamp"
                time_elapsed_in_minutes=$(echo "($merged_timestamp - $first_commit_timestamp) / 60" | bc)
                echo "time in minutes between base commit and merge: ${time_elapsed_in_minutes}m"

                last_commit_timestamp="$(git show -s --format=%ci ${{github.event.pull_request.head.sha}})"
                echo "head commit time using 'git show -s --format=%ci <COMMIT HASH>': $last_commit_timestamp"

                last_commit_timestamp=$(git log -1 --format=%ct ${{github.event.pull_request.head.sha}})
                echo "head commit time using 'git log -1 --format=%ct <COMMIT HASH>': $last_commit_timestamp"
                time_elapsed_in_minutes=$(echo "($merged_timestamp - $last_commit_timestamp) / 60" | bc)
                echo "time in minutes between head commit and merge: ${time_elapsed_in_minutes}m"
