name: triggered by PR merge

on:
    pull_request:
        types: [closed]

jobs:
    do-the-thing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: attempt to print the secret
              run: |
                my_magical_secret="${{secrets.MY_MAGICAL_SECRET}}"
                echo "hello world: ${my_magical_secret}"
                echo "goodbye world: ${my_magical_secret}"
            - name: print out the merged PR's details
              run: |
                echo "PR number: ${{github.event.pull_request.number}}"
                echo "PR title: ${{github.event.pull_request.title}}"
                echo "PR body: ${{github.event.pull_request.body}}"
                echo "PR merged: ${{github.event.pull_request.merged}}"
                echo "PR merged by: ${{github.event.pull_request.merged_by}}"
                merged_time="${{github.event.pull_request.merged_at}}"
                echo "PR merged at: $merged_time"
                echo "PR merge commit SHA: ${{github.event.pull_request.merge_commit_sha}}"
                echo "full event body: ${{github.event}}"
                echo "event body name: ${{github.event_name}}"
                # get time of the commit that triggered the PR merge
                commit_time="$(git show -s --format=%ci ${{github.event.pull_request.merge_commit_sha}})"
                echo "commit time: $commit_time"

                current_timestamp=$(date +%s)
                last_commit_timestamp=$(git log -1 --format=%ct ${{github.event.pull_request.merge_commit_sha}})
                time_elapsed_in_minutes=$(echo "($current_timestamp - $last_commit_timestamp) / 60" | bc)
                echo "time_elapsed_in_minutes: ${time_elapsed_in_minutes}m"
