name: triggered by PR merge

on:
    pull_request:
        types: [closed]

jobs:
    do-the-thing:
        runs-on: ubuntu-latest
        steps:
            - run: |
                my_magical_secret="${{secrets.MY_MAGICAL_SECRET}}"
                echo "hello world: ${my_magical_secret}"
                echo "goodbye world: ${my_magical_secret}"
